language: csharp
mono: 4.6.2
dist: xenial
solution: HomeGenie_Linux/HomeGenie_Linux.sln
before_install:
  sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
  sudo apt install apt-transport-https
  echo "deb https://download.mono-project.com/repo/ubuntu stable-xenial main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list
  sudo apt update
install:
  - nuget restore HomeGenie_Linux/HomeGenie_Linux.sln
  - nuget install NUnit.ConsoleRunner -Version 3.9.0 -OutputDirectory testrunner
before_script: 
script:
- xbuild /p:Configuration=Debug HomeGenie_Linux/HomeGenie_Linux.sln
- mono ./testrunner/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe ./HomeGenie.Tests/bin/Debug/HomeGenie.Tests.dll
after_success:
- HomeGenie_Linux/Packager/builddeb.sh
after_failure: 
deploy:
  provider: releases
  api_key:
    secure: UddT9q0YRxhD0ce4cRZrkmb5CDDeDwGVyOEO0koWFFwHIsqszQ8i6NgHJRF0+fmD9OLT65rONUbsZz1SG01gwdYy0aX46BdIRDz63Cs7TXZugoKu8ZagmXra8bb5nirJR6E54lCZrcma0zp0JlpOH6fAgWuG24LaWhmA4N8k4XNaLIQX9uHD7jTTK6gcq8JXaFA4UgXE6DwdkbGiPTUIdtHmuoEuTtW/djnkPwoE2ViqbAJfqJoxYJmce7v/C49enwqk9hSJ029r22hjtRpvsX02ZxPFXa7mR+310Jj+yRQWh4cCYZ+WfKqgpwNdQqvvT9HNslzLmP5WHVx5o0FOi96LC04HdezVqQhn2IkGMtc55qXoIC96vTwlUtmRMiD3XyUe8CJdp2tqL0tAnHbdNFqOgK5f0q6gM46KqEHP2aTDZaug4KGyairPR3Uw/Zx0pUy4a+ZBFg2myjKofdLKLMHMbIuWv1oSbY+5warxCTBUpx7NUP/JfQyrZwdQivjuqp+D7SvML66J56mzQ1/l9ExiTtKKFV0HpmJvmWFaucaYQBhy3i7+UafApPu8aFVTF6Fe/DovDfLV2/KBgUjhxPCeHRV7IXr3BOTfrpJQbr75SYkfjzFkT80ExELssUCo3oGk7T1V2RMlvVvL44yb6cGddXqsgmbdtqrkTdorhK4=
  file_glob: true
  file: HomeGenie_Linux/Packager/Output/*
  skip_cleanup: true
  on:
    tags: true
    branch: master
    repo: genielabs/HomeGenie

