version: 1.0.{build}
branches:
  except:
  - gh-pages
image: Visual Studio 2015
configuration: Debug
before_build:
  - nuget restore .\HomeGenie\packages.config -SolutionDirectory .\HomeGenie_Windows
build:
  project: .\HomeGenie_Windows\HomeGenie_VS10.sln
  verbosity: minimal
test:
  assemblies:
    only:
      - HomeGenie.Tests/bin/Debug/HomeGenie.Tests.dll
after_test:
- cmd: >-
    echo "Bundling installer for HomeGenie %APPVEYOR_REPO_TAG_NAME%"
    
    dir "HomeGenie\bin\Debug"

    cd "HomeGenie_Windows\Packager\"

    "C:\Program Files (x86)\Inno Setup 5\iscc.exe" /Q /F"HomeGenie_%APPVEYOR_REPO_TAG_NAME%" setup.iss

    echo "Adding artifact"

    appveyor PushArtifact "Output\HomeGenie_%APPVEYOR_REPO_TAG_NAME%.exe"

deploy:
  release: $(APPVEYOR_REPO_TAG_NAME)
  description: 'HomeGenie $(APPVEYOR_REPO_TAG_NAME)'
  provider: GitHub
  auth_token:
    secure:  1aMBEFi1qBAoV4H+LYx7hoVLgXJfndGoQ8I8qjLsoxXNA1zS+zgQHi2zVlRrmw1v
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true

